CREATE DATABASE SSAFYMINI;

USE SSAFYMINI;

DROP TABLE IF EXISTS USERS ;

CREATE TABLE USERS(
	USERNO INT PRIMARY KEY AUTO_INCREMENT,
    ID VARCHAR(30) UNIQUE NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    AGE INT NOT NULL,
    GENDER CHAR(1) NOT NULL,
    PHONE VARCHAR(12) NOT NULL,
    BIRTH VARCHAR(12) NOT NULL,
    GRADE VARCHAR(20) NOT NULL DEFAULT 'USER',
    CREATETIME DATE NOT NULL DEFAULT (CURRENT_DATE)
);

SELECT * FROM USERS;

SELECT CONCAT(1996, 10, 12);